name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:       [ubuntu-latest, windows-latest]
        nim-channel:    [stable]  # , devel] devel and windows are not supported.
    name: ${{ matrix.platform }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Nimble setup
      run: |
        nimble -y refresh
        nimble -y install

    - name: Build
      run: |
        pgxtool
        pgxtool available-hooks
        pgxtool create-project test
        pgxtool create-hook emit_log
