name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:       [ubuntu-latest, windows-latest]
        nim-channel:    [stable]  # , devel] devel and windows are not supported.
    name: ${{ matrix.platform }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name:  Windows Dev dependencies setup
      if: runner.os == 'Windows' 
      run: |
        Write-Host "Installing WinGet PowerShell module from PSGallery..."
        Install-PackageProvider -Name NuGet -Force | Out-Null
        Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null
        Repair-WinGetPackageManager
        winget install PostgreSQL.PostgreSQL.16 --disable-interactivity
     

    - name: Linux Dev dependencies setup      
      if: runner.os == 'Linux'
      run: |
        sudo apt -y update
        sudo apt --purge remove postgresql-* libpq5 libpq-dev -y
        sudo apt -y install build-essential postgresql postgresql-contrib libpq5 libpq-dev postgresql-server-dev-all

    - name: Nimble setup
      run: |
        nimble -y refresh
        nimble -y install

    - name: Build
      run: |
        pgxtool
        pgxtool available-hooks
        pgxtool create-project test
        pgxtool create-hook emit_log
        pgxtool build-extension test
